version: '3.7'

services:
  ammo-puppet:
    build: ./puppet
    container_name: ammo-puppet
    init: true
    privileged: true
    restart:
      always
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./puppet/ammo.js:/home/pptruser/index.js:ro
    entrypoint: ['node', '/home/pptruser/index.js']

  primer-puppet:
    build: ./puppet
    container_name: primer-puppet
    init: true
    privileged: true
    restart:
      always
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./puppet/primers.js:/home/pptruser/index.js:ro
    entrypoint: ['node', '/home/pptruser/index.js']

  backend:
    image: 'backend'
    build: ./backend
    container_name: 'backend'
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      AMMO_SLACK_URL: ${AMMO_SLACK_URL}
      RELOADING_SLACK_URL: ${RELOADING_SLACK_URL}

  mongodb:
    image: 'mongo'
    container_name: 'mongo'
    ports:
      - 27017:27017
    volumes:
      - puppet-mongo:/data/db

volumes:
  puppet-mongo: